- playbooks/all.yml
- playbooks/certificates.yml
- roles/certificates/defaults/main.yml
- roles/certificates/files/.gitignore
- roles/certificates/tasks/copy_to_host.yml
- roles/certificates/tasks/generate_certificate_authority.yml
- roles/certificates/tasks/generate_host_csr.yml
- roles/certificates/tasks/sign_certificates.yml
- roles/system/tasks/packages.yml
- topology.ini
> 4 add role for certificate

- roles/chrony/templates/chrony.conf.j2
- roles/system/defaults/main.yml
- roles/system/tasks/packages.yml
> Support Centos 8

- README.md
> docs: add sections for using playbooks and roles

- README.md
- playbooks/all.yml
- playbooks/ldap_kerberos.yml
- roles/ldap_kerberos/defaults/main.yml
- roles/ldap_kerberos/handlers/main.yml
- roles/ldap_kerberos/tasks/create_users_keytab.yml
- roles/ldap_kerberos/tasks/install_kerberos_client.yml
- roles/ldap_kerberos/tasks/install_kerberos_server.yml
- roles/ldap_kerberos/tasks/install_openldap_server.yml
- roles/ldap_kerberos/tasks/main.yml
- roles/ldap_kerberos/tasks/openldap_servers_repo.yml
- roles/ldap_kerberos/tasks/packages.yml
- roles/ldap_kerberos/tasks/sssd.yml
- roles/ldap_kerberos/templates/kadm5.acl.j2
- roles/ldap_kerberos/templates/kdc.conf.j2
- roles/ldap_kerberos/templates/kerberos_ldap_creds.j2
- roles/ldap_kerberos/templates/krb5.conf.j2
- roles/ldap_kerberos/templates/slapd.conf.j2
- roles/ldap_kerberos/templates/sssd.conf.j2
- roles/system/tasks/disable_firewalld.yml
- roles/system/tasks/main.yml
- topology.ini
> Add ldap_kerberos role

- README.md
- roles/ldap_kerberos/defaults/main.yml
- roles/ldap_kerberos/templates/kdc.conf.j2
- roles/ldap_kerberos/templates/krb5.conf.j2
Fixes #11 
Added a `max_renewable_life` parameter to realm configuration.
Moved `renew_lifetime` from `kdc.conf.j2` to `krb5.conf.j2`, since it's a client configuration and not server.
Here's a diff on a principal attributes before and after deploying with this configuration:
```diff
[root@edge-01 ~]# kadmin -p admin/admin -w admin123 -q "getprinc tdp_user"
Authenticating as principal admin/admin with password.
Principal: tdp_user@REALM.TDP
Expiration date: [never]
Last password change: Wed Aug 24 13:13:01 UTC 2022
Password expiration date: [never]
Maximum ticket life: 1 day 00:00:00
-Maximum renewable life: 0 days 00:00:00
+Maximum renewable life: 7 days 00:00:00
Last modified: Wed Aug 24 13:13:01 UTC 2022 (admin/admin@REALM.TDP)
Last successful authentication: [never]
Last failed …
```
> Make tickets renewable

- README.md
- playbooks/ldap_kerberos.yml
- roles/ldap_kerberos/defaults/main.yml
- roles/ldap_kerberos/handlers/main.yml
- roles/ldap_kerberos/tasks/install_kdcproxy.yml
- roles/ldap_kerberos/tasks/install_kerberos_client.yml
- roles/ldap_kerberos/templates/kdcproxy-httpd.conf.j2
- roles/ldap_kerberos/templates/kdcproxy.conf.j2
- roles/ldap_kerberos/templates/krb5.conf.j2
- roles/ldap_kerberos/templates/ssl-httpd.conf.j2
- topology.ini
> feat: add kdcproxy tasks

- README.md
- playbooks/all.yml
- playbooks/postgresql.yml
- roles/postgresql/defaults/main.yml
- roles/postgresql/handlers/main.yml
- roles/postgresql/tasks/configure.yml
- roles/postgresql/tasks/main.yml
- roles/postgresql/tasks/packages.yml
- roles/postgresql/tasks/public_repo.yml
- roles/postgresql/tasks/users_databases_schemas.yml
- roles/postgresql/templates/pg_hba.conf.j2
- topology.ini
The role is designed to deploy a PostgreSQL server. Client configuration is missing and will be added in future PR when needed.
Fixes #6 
> Add postgresql role

- playbooks/postgresql.yml
- topology.ini
> feat(postgresql): add public repo for PostgreSQL clients

- topology.ini
`tdp-collection` needs a ldap group
Fixes #18 
> feat: add ldap group

- galaxy.yml
> feat: add Ansible galaxy file

- playbooks/chrony.yml
Fixes #30 
This PR adds a specific playbook for Linux container hosts. This can be useful for teams running TDP on LXD containers.
> Add Linux containers support

- roles/system/defaults/main.yml
- roles/system/tasks/disable_firewalld.yml
> Do not interfere with firewalld if not installed

- roles/system/defaults/main.yml
> fix(system): add missing tar package

- roles/ldap_kerberos/tasks/sssd.yml
> Support hosts without sssd-kcm or authselect

- roles/ldap_kerberos/tasks/install_openldap_server.yml
> fix(ldap): set correct permissions on configuration files

- roles/postgresql/defaults/main.yml
- roles/postgresql/tasks/configure.yml
Fixes #22
Note: as the PR updates PostgreSQL configuration parameter, the parameter ```maintenance_work_mem``` is also modified for memory tuning optimization (this was forgetten with the previous changes).
> postgres: move log to /var/log/postgresql

- roles/postgresql/defaults/main.yml
> postgres: remove public schema creation for hive database

- playbooks/system.yml
- roles/system/defaults/main.yml
- roles/system/tasks/cgroups.yml
> cgroups: install and enable cgroups

- roles/postgresql/tasks/users_databases_schemas.yml
> postgres: fix to use postgres users passwords in defaults/main.yml

- roles/system/defaults/main.yml
> system: add python lxml package on rocky8

- playbooks/postgresql.yml
- roles/postgresql/defaults/main.yml
- roles/postgresql/tasks/packages_client.yml
- topology.ini
This PR installs python adapter package for postgres client which is not the case actually.
> feat: install python adapter package for postgres client

- topology.ini
Fixes #67 
Relates to
- https://github.com/TOSIT-IO/tdp-collection/pull/700
- https://github.com/TOSIT-IO/tdp-collection-extras/pull/102
> refactor: remove tdp-collection groups from topology

- roles/system/tasks/hosts.yml
> Add alias with FQDN trailing dot in /etc/hosts

- roles/postgresql/defaults/main.yml
- roles/postgresql/tasks/users_databases_schemas.yml
> postgres: add prerequisites for postgres_exporter

- playbooks/system.yml
- roles/postgresql/defaults/main.yml
- roles/system/tasks/redis.yml
- topology.ini
> feat: airflow postgresql

- roles/postgresql/tasks/users_databases_schemas.yml
> postgresql: use postgresql_membership module to manage groups

- roles/system/defaults/main.yml
This PR install R on the cluster for the sparkR installation.
fixes #84
Requires :
> feat(R): r installation

- playbooks/system.yml
- roles/system/tasks/python38.yml
Add python 3.8 prerequisite for Hue 4.11
> feat: install python 3.8 for Hue 4.11

- roles/chrony/tasks/main.yml
> fix-install chrony added for images not already containing the service

- roles/postgresql/defaults/main.yml
> postgres: add user database schema for grafana

- README.md
Fixes none
Following [the discussion](https://github.com/orgs/TOSIT-IO/discussions/92)
> docs: fix title

- roles/postgresql/defaults/main.yml
Part of the issue https://github.com/TOSIT-IO/tdp-observability/issues/88
> postgres: remove prerequisites for postgres_exporter

- playbooks/kdcproxy_server_restart.yml
- playbooks/kdcproxy_server_start.yml
- playbooks/kdcproxy_server_stop.yml
- playbooks/kerberos_server_restart.yml
- playbooks/kerberos_server_start.yml
- playbooks/kerberos_server_stop.yml
- playbooks/openldap_server_restart.yml
- playbooks/openldap_server_start.yml
- playbooks/openldap_server_stop.yml
- playbooks/postgresql_server_restart.yml
- playbooks/postgresql_server_start.yml
- playbooks/postgresql_server_stop.yml
- playbooks/sssd_server_restart.yml
- playbooks/sssd_server_start.yml
- playbooks/sssd_server_stop.yml
- roles/ldap_kerberos/tasks/restart_httpd.yml
- roles/ldap_kerberos/tasks/restart_kerberos.yml
- roles/ldap_kerberos/tasks/restart_openldap.yml
- roles/ldap_kerberos/tasks/restart_sssd.yml
- roles/ldap_kerberos/tasks/start_httpd.yml
- roles/ldap_kerberos/tasks/start_kerberos.yml
- roles/ldap_kerberos/tasks/start_openldap.yml
- roles/ldap_kerberos/tasks/start_sssd.yml
- roles/ldap_kerberos/tasks/stop_httpd.yml
- roles/ldap_kerberos/tasks/stop_kerberos.yml
- roles/ldap_kerberos/tasks/stop_openldap.yml
- roles/ldap_kerberos/tasks/stop_sssd.yml
- roles/postgresql/tasks/restart.yml
- roles/postgresql/tasks/start.yml
- roles/postgresql/tasks/stop.yml
> feat: add restart playbooks for openldap/kerberos/postgres servers

- roles/system/defaults/main.yml
> feat: bc missing

- roles/ldap_kerberos/tasks/install_openldap_server.yml
- roles/ldap_kerberos/templates/slapd.conf.j2
- roles/ldap_kerberos/templates/slapd_password.conf.j2
> feat: secure ldap rootpw

- roles/postgresql/defaults/main.yml
Fixes None
Upgrades Postgres version to 17.4 to this date. tested with TDP stack 1.1 and stack 2.0.
> feat(postgres): updated postgres to version 17
